### ISSUE TITLE
Множественная компиляция

### ISSUE THREAD

**Issue by pafnuty** [info-expert-projects/LessForBitrix#2]
При использовании цветовых схем часто требуется множественная компиляция, по одному css на каждую цветовую схему.
Необходимо реализовать такую возможность.
@antares-me, @dmalshin есть идеи?

**Comment by dmalshin** [comment]
Закрепить 80-89 файлы за файлами темы и если есть 80-main-orange.less и 81-main-blue.less компилить два результирующих файла.
Хотя как между ними переключаться?

**Comment by pafnuty** [comment]
@dmalshin суть в том, что на выходе должно быть N файлов.
По сути нужно запускать компилятор в цикле, но для каждой итерации нужны свои настройки.
Я пока не понимаю как можно сделать множественную настройку.

**Comment by dmalshin** [comment]
Цветовые схемы отличаются цветовыми переменными. Соответственно по логике должны быть разные файлы с этими переменными.
И foreach "файлСПеременными" проводить итерацию)

**Comment by pafnuty** [comment]
@dmalshin когда пойдём на обед — объясню проблему на пальцах :)
